# Site settings
title: LeanMeanTech
email: hello@leanmeantech.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: leanmeantech

# Build settings
markdown: kramdown
